post https://codplayscod-bot.qmarsala.workers.dev/
Content-Type: application/json
Accept: application/json

{
    "status": "crashed"
}

###

post https://codplayscod-bot.qmarsala.workers.dev/
Content-Type: application/json
Accept: application/json

{
    "status": "closed"
}